---


- name: restart machine
  become: true
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  tags:
    - restart
    - now

- name: restart wait
  become: false
  local_action: wait_for host="{{ inventory_hostname }}" search_regex="Welcome to Ubuntu" delay=20 timeout=300
  tags:
    - restart
    - wait
