---

- name: restart machine
  become: true
#  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  shell: nohup bash -c 'sleep 2 && shutdown -r now "Ansible updates triggered"' &
  async: 0
  poll: 0
  ignore_errors: true
#  when: reboot.stdout.find('yes') != -1
  tags: ['reboot', 'restart']

- name: restart wait
  become: false
  local_action: wait_for host={{ ansible_host | default(inventory_hostname,boolean=True) }} search_regex='OpenSSH' port=22 state='started' delay=15 timeout=300
  tags: ['reboot', 'restart']
